<?php
/**
 * @link      http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license   http://www.yiiframework.com/license/
 */

namespace yii\adminUi\assetsBundle;

use yii\web\AssetBundle;

/**
 * Asset bundle for the Twitter bootstrap css files.
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since  2.0
 */
class AdminUiAsset extends AssetBundle {
    public $sourcePath = '@vendor/almasaeed2010/adminlte/dist/';
    public $baseUrl = '@web';

    public $depends = [
        'yii\web\JqueryAsset',
        'yii\bootstrap\BootstrapAsset',
        'yii\bootstrap\BootstrapPluginAsset',
        'yii\adminUi\assetsBundle\FontAwesomeAsset',
        'yii\adminUi\assetsBundle\FontIoniconsAsset',
    ];

    public function init() {
        if (true === YII_DEBUG || 'dev' === YII_ENV) {
            $this->css[] = 'css/AdminLTE.css';
            $this->css[] = 'css/skins/_all-skins.css';
            $this->js[]  = 'js/app.js';
        } else {
            $this->css[] = 'css/AdminLTE.min.css';
            $this->css[] = 'css/skins/_all-skins.min.css';
            $this->js[]  = 'js/app.min.js';
        }

        parent::init(); // TODO: Change the autogenerated stub
    }
}